### ISSUE TITLE
Annotation display issues

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/fv-website#8]
Running locally, I'm able to pull up annotations but am getting some display issues on both Firefox (71.0) and Safari (Version 13.0.3 (14608.3.10.10.1))

<img width="485" alt="Screen Shot 2019-12-12 at 5 36 14 PM" src="https://user-images.githubusercontent.com/4392604/70754959-8d8c1a80-1d06-11ea-8813-60ef21cee957.png">

on first loading they show up like this, then once I start to scroll down...

<img width="514" alt="Screen Shot 2019-12-12 at 5 36 17 PM" src="https://user-images.githubusercontent.com/4392604/70754985-a3014480-1d06-11ea-903f-2ad62d721cef.png">

**Comment by raffazizzi** [comment]
This issue straddles this repo and the viewer's https://github.com/FrankensteinVariorum/viewer .

The CSS that causes this to happen is in the viewer; it keeps the variants / annotation box "sticky". I could make sure that the annotations are all in the same box so that they'd all be sticky, but if there are many, the user would not be able to see the ones at the bottom as the first one will always be at the top of their screen. 

I'm not sure what to do about this. I could force the annotations not to be sticky, but then if the user clicked to read the annotations to the last paragraph they a) not see that the annotation has been displayed and b) they would have to scroll up to see it.

Another alternative, perhaps better, would be to limit the size of the variant/annotation box to the available screen size and if the content overflows, add a scroll bar. Not very elegant but likely functional. I'm going to try to implement this and see what happens

**Comment by raffazizzi** [comment]
Fixed with https://github.com/FrankensteinVariorum/viewer/commit/c01841207afe0a619620a9b354685d36b9f70237
